apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-claim
  namespace: default
  # labels:
  #   app: mssql-claim
spec:
  # storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Mi